# Commit taken from https://gitlab.haskell.org/ghc/ci-images
variables:
  DOCKER_REV: 769e7fbb291427fb70c19fad4f98bb976cdc4c91

validate-hadrian:
  image: "registry.gitlab.haskell.org/ghc/ci-images/x86_64-linux-deb10:$DOCKER_REV"
  tags:
    - x86_64-linux
  before_script:
    - git clean -xdf
    - $GHC --version
    - cabal --version
  script:
    - git submodule update --init --recursive
    - $GHC --version
    - cabal update
    - cabal new-run -w $GHC nofib-run -- -o out -w "$GHC"
    - mkdir -p results
    - $GHC --info > results/compiler-info
    - cp _make/out/*.results.tsv results
  artifacts:
    paths:
      - results
